### ISSUE TITLE
P2 Repository merges plugins with different versions in content.xml

### ISSUE THREAD

**Issue by kdoteu** [eclipse/packagedrone#10]
Don't know if this is related to #4 but from my perspective it's a different problem.

We have a Feature with different Guava versions. In Packagedrone and in my build everything looks perfect.
![feature_perspective](https://cloud.githubusercontent.com/assets/3602457/12326868/8cfe17a6-bad3-11e5-9a05-c75aae94bfa3.png)

But in Eclipse I only get the latest version of guava.
![eclipse_view](https://cloud.githubusercontent.com/assets/3602457/12326881/aa682c46-bad3-11e5-8857-b2bb2293caac.png)

As far I could see its wrong decoded in the content.xml of the P2 repository.
![content xml](https://cloud.githubusercontent.com/assets/3602457/12327002/4ebd7e9a-bad4-11e5-990e-ea04e520a789.png)

As you can see in the feature 'others.feature' only one Guava version is listed. Some lines above you can see the other versions but they are not inlcuded in the feature.

Don't know how the repo is generated and if this 'bug' really realates to packagedrone.

**Comment by ctron** [comment]
This is a good question ... the first information is: Who generated the P2 index data. Package Drone or Tycho?

Package Drone can re-use the Tycho P2 index data which is uploaded during the Maven 2 deploy process. Or it can create its own P2 index data.

In the latter case, this would be an issue with Package Drone. In the first case it would look like an issue with Tycho.

**Comment by kdoteu** [comment]
We are generated the features with eclipse and used the export wizard. So this is a Package Drone issue.

**Comment by ctron** [comment]
Ok, then this looks like a bug in package drone. I will try to look into this today.

**Comment by ctron** [comment]
Ok ... to me this looks like the transformation from `FeatureInformation` to `InstallableUnit` [1] is the cause for this.

The requirements key is only the name of the requirement, where the Feature Information is equal by id + version.

[1] [InstallableUnit.java:447](/eclipse/packagedrone/blob/master/bundles/org.eclipse.packagedrone.repo.aspect.common/src/org/eclipse/packagedrone/repo/aspect/common/p2/InstallableUnit.java#L447)

**Comment by kdoteu** [comment]
Now its working perfect. Thanks for the fast solution!

![solved_content xml](https://cloud.githubusercontent.com/assets/3602457/12353124/2108dcb6-bb8c-11e5-81f5-1f609831a0c4.png)
