### ISSUE TITLE
Duplicate entry for Channels

### ISSUE THREAD

**Issue by dcominottim** [eclipse/packagedrone#102]
Using version 0.14.0.20160608-1431 after a fresh install on CentOS 7, whenever I add a new Channel, I see a duplicate entry in the Channel listing:

![drone](https://cloud.githubusercontent.com/assets/4914233/22382979/0f24e696-e4af-11e6-825f-c97c0f7d22b7.PNG)

How can I see entries only for alias names?

**Comment by ctron** [comment]
It is not a bug, it's a feature ;-) you will see an entry for each alias in addition.

**Comment by dcominottim** [comment]
Oh, thanks for the clarification. :)
