### ISSUE TITLE
Service starts before network devices are loaded

### ISSUE THREAD

**Issue by kdoteu** [eclipse/packagedrone#12]
I noticed some problems autostarting packagedrone on my server.
Package Drone try to start before I got my network devices to run. That causes my system to hang during system start. (After changing the init.d-script I got my system back to work.)
So i tried a bit around.
* Removing the /etc/rc2.d/S17packag... did nothing because server starts in runlevel 2 ^^ But my Server starts (without Package Drone)
* Moving /etc/rc2.d/S17packagedrone to S18 did nothing too.

All things back to normal.

Workaround: Moving /etc/rc2.d/S17package ... to /etc/rc2.d/K17packagedrone so its going to be ignored during startup

Debian (SysV): 3.2.68
Package Drone Version:  Package Drone 0.12.0.20151216-1114

**Comment by ctron** [comment]
Which startup script are you using? I can't remember making a Debian start script.

**Comment by kdoteu** [comment]
I've only installed the .deb package. Don't know who provided and registered the startup-script.

**Comment by ctron** [comment]
Ok, but then it is the upstart script? Right?

The SysV startup script is only added to the CentOS 6 RPM.

**Comment by kdoteu** [comment]
This is the script i found
```
#! /bin/sh
# /etc/init.d/blah
#

# Some things that run always
touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script blah "
    exec /usr/lib/package-drone-server/instance/server
    echo "Could do more here"
    ;;
  *)
    echo "Usage: /etc/init.d/package-drone {start}"
    exit 1
    ;;
esac

exit 0


exec /usr/lib/package-drone-server/instance/server
```

Don't know if this is the upstart or SysV script, thats not my area of expertise.

**Comment by ctron** [comment]
I would guess this is neither :confused:  ... But it also does not come from Package Drone. Maybe somebody else wrote that script.

You can have a look at all the files provided by the Package Drone DEB using:
```
dpkg -L org.eclipse.packagedrone.server`
```

But if you are running on Debian I guess we need a new feature "Debian Startup Script".

**Comment by ctron** [comment]
In the end, this script just switches (not forks) to Package Drone any no other script will be called after this.

Meaning that your SysV startup process is switched to the Package Drone server.

Removing the "exec" and adding a "&" at the end of the line will, at least, fork off the server process.

**Comment by kdoteu** [comment]
Switching to forking the process solved the starting issue. But who provided this script? It came with the deb-installation.

**Comment by ctron** [comment]
The file your mentioned is the upstart script for Ubunt's upstart init daemon. This one is provided in the .deb file. So what makes you think it came with the Debian script? Did the `dpkg -L` command list this file?

So maybe there is some process on debian which converts upstart scripts into SysV script. I don't know much about debian, I have to admit.

So if you can give me a bit more information about your system setup I can try and reproduce the issue.

**Comment by kdoteu** [comment]
I said nothing ... after a long time of thinking about this "project" I recognised I used this server before for the same application. And so there is a possibility that I wrote this script. ... I totally forgotten I tried  Package Drone before :+1: 

Sorry for the issue ;p

**Comment by ctron** [comment]
No problem at all! :smile: 

I am just glad to know that no file sneaked into the .deb!

**Comment by ctron** [comment]
Since I am not that familiar with Debian. Would it be a good idea to create a new issue for providing a Debian specific package? Is Debian using systemd in the future?
