### ISSUE TITLE
Move RPM code to "Eclipse Packager"

### ISSUE THREAD

**Issue by ctron** [eclipse/packagedrone#137]
The code generating RPM packages for Linux, should be moved to the new "Eclipse Packager" project, which will be the home for creating software packages for Linux.

This will impact the current issue #136 and #130.

**Comment by dwalluck** [comment]
You've moved the code and I've implemented fixes for both  issue #136 and #130.

**Comment by ctron** [comment]
Indeed. Thanks for your help!
