### ISSUE TITLE
not-working resolution of manifest-values from plugin.properties (version 0.11.4)

### ISSUE THREAD

**Issue by afischer211** [eclipse/packagedrone#2]
If I have an OSGi-bundle, where some variables are used in the Manifest (eg. %vendor) and the value for the variables is defined in a file **/plugin.properties** (at root of the jar-file), all is ok - if (and only if) the file is named **plugin.properties** and the entry **Bundle-Localization: plugin** is contained in the manifest.
I think, in regular p2-repositories the manifest-variables (not other variables in "plugin.xml" or so) are resolved also without the entry inside the manifest.
One not working example is the bundle **com.google.guava** at version **10.0.1.v201203051515**.
If I add manually a file "plugin.properties" to the root of the jar and also the entry into the manifest, the resolution works.

**Comment by ctron** [comment]
I just checked the definition of the `Bundle-Localization` header. It does have a default value of `OSGI-INF/l10n/bundle`.

This default is currently not considered by Package Drone. So this is definitely a bug. Thanks again for reporting!

**Comment by ctron** [comment]
Also see: http://wiki.osgi.org/wiki/Bundle-Localization
