### ISSUE TITLE
Create a bundle information overview

### ISSUE THREAD

**Issue by ctron** [eclipse/packagedrone#23]
Currently there is already a list registered bundles. Including their OSGi state.

However there should be some "legal" style, "about dialog"-ish overview screen, showing all bundles and integrating their license and legal information.

**Comment by riyafa** [comment]
I would like to work on this to familiarize myself with the codebase of package drone so that I could submit a proposal for GSoC this time.

**Comment by ctron** [comment]
Package Drone should provide an overview what software components is consists of. There also is a requirement for each Eclipse project to have an `about.html` file in each OSGi bundle, which contains the license text. OSGi itself has a `Bundle-License` [1] header which can either be a license name and/or URL to a license.

Package Drone already has a "list of bundles" view [2], which shows the currently installed bundles, but this screen is missing the "legal" information, like the license, the provider, …

Either this screen should be enhanced or a new screen should be made which at least provides:
- The bundle symbolic ID
- The bundle name and version
- The vendor name
- If present a link to the license. Either by the means of an embedded `about.html` or the `Bundle-License` header value
- And maybe any additional legal information which is present in the `MANIFEST.FM` file


[1] http://wiki.osgi.org/wiki/Bundle-License
[2] http://localhost:8080/system/info/framework/bundle

**Comment by riyafa** [comment]
I will start working on this issue and report progress and ask if I encounter any problem

**Comment by ctron** [comment]
Sounds great! Please assign yourself to the issue as long as you are working on it :+1:

**Comment by riyafa** [comment]
Yes I would like to be assigned to this issue. I am working on it. As I understand the current "list of bundles" view [1] should be improved so that with each bundle listed, the link to the license if present would also be listed.

[1] http://localhost:8080/system/info/framework/bundles

**Comment by ctron** [comment]
I just checked for your email address and it seems that there is no CLA for it registered with Eclipse.

Since a CLA is mandatory for accepting contributions I would kindly ask you to sign the CLA first.

**Comment by riyafa** [comment]
I signed a CLA with my git email address that is: riyafa0@gmail.com .

**Comment by ctron** [comment]
Ok, so you have to check on the source code with that email.

**Comment by ctron** [comment]
Ok, looks like assigning users only works that way with personal repositories. Can you assign yourself?

**Comment by riyafa** [comment]
I can't assign myself unless I am a contributor. Can I make a pull request if I complete the task?

**Comment by ctron** [comment]
Sure. I guess that's the way to go. It also is the first time for me doing this being an Eclipse GitHub project. So thanks for your patience.

**Comment by ctron** [comment]
So I removed the "help wanted" label instead.

**Comment by ctron** [comment]
Re-adding "help wanted".
