### ISSUE TITLE
Channelname with spaces produces Http-500 Error

### ISSUE THREAD

**Issue by kdoteu** [eclipse/packagedrone#26]
If you try to configure a channelname containing a space between two words a exception will occur.

[spaceName.txt](https://github.com/eclipse/packagedrone/files/103453/spaceName.txt)

PackageDrone Version: Package Drone 0.12.0.20151216-1114

**Comment by ctron** [comment]
Which says: `Channel name must match pattern: [a-zA-Z0-9\-_\.]+`

But I admit. This is not user friendly.

**Comment by ctron** [comment]
Thanks for reporting! :+1:

**Comment by kdoteu** [comment]
It worked a build-version before, thats the reason I tried this. 
Glad you fixed it so fast ;D
