### ISSUE TITLE
Invalid P2 artifact mappings generated in ZIP file

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse/packagedrone#29]
The p2 metadata plugin generates invalid metadata (at least if you download the repository as a zip file). The issue comes from the file artifacts.xml where the path of the bundles and features (and binary resources) are invalid.

The path is `${repoUrl}/plugins/${id}/${version}/${id}_${version}.jar`
It should be `${repoUrl}/plugins/${id}_${version}.jar`

See http://i.imgur.com/pN4Mgt2.png

Keep up the great work!

**Comment by ctron** [comment]
True! I did not look into this, but my guess is that the same rules are added for the hosted and zipped version of the repository.

However the zipped version does follow the "classic" archive layout with `plugins` and `features`, where the hosted version does require a bit more extra information which is encoded in the URL.

So I guess this can be resolved either by fixing the rules, or by changing the layout to match the rules.

**Comment by ctron** [comment]
will be in version 0.13.0
