### ISSUE TITLE
Wrong warning message in Channel > Help > API Upload section (v0.11.5)

### ISSUE THREAD

**Issue by Falx** [eclipse/packagedrone#3]
On top of the page the warning message:
>All further information in this page requires the channel to have at least one deploy key assigned. However there are currently no deploy groups/keys assigned to this channel, so it will not be possible to authenticate. Assign deploy groups now.

is present, although a deploy group is already assigned to the channel.

**Comment by ctron** [comment]
Thanks for reporting this. I will check it in a few days though. Christmas is coming 🎄

**Comment by Falx** [comment]
Indeed it is, enjoy the holidays! ;-)

**Comment by ctron** [comment]
I just dug into this issue and saw that is should be fixed in a more recent build. This issue is fixed with commit f68853978deb921ca1cd02100898cc15ba430629.

Could you please try a more recent version of the 0.12.x branch and re-test. Thanks!

**Comment by ctron** [comment]
FWIW: I found another bug in the current development version by looking into this issue :wink:  So thanks!
