### ISSUE TITLE
Wrong download URL for R5 OSGi bundles

### ISSUE THREAD

**Issue by Falx** [eclipse/packagedrone#34]
I configured our jenkins build server to export to pdrone via de deployer plugin.
However it seems to upload the whole path structure. If I for instance set it to upload from `pdrone/folder/*`, the uploaded artifacts will be called: `pdrone/folder/bundle1.jar`, `pdrone/folder/bundle2.jar` etc.. 

I don't know if this is the cause of my issue, but when I use the pdrone r5 link as a source in an eclipse bndtools project, it can read the index.xml just fine, but the download links it uses from that file don't seem to work. 

I suspect this is because of that prefix path, since a manual uploaded jar does work..

**Comment by ctron** [comment]
This looks indeed like a bug. The index file uses `/<channel-id>/artifact/<artifact-id>/<artifact-name>` as pattern for generating the link to the resource.

Actually the name is not important, it is just done to have a human friendly download URL, the core information is the artifact ID. However the download handler does not take into account that the artifact name could include a slash.

**Comment by ctron** [comment]
For me the correct fix sounds like simply allowing the download, no matter if the (optional) name contains slashes or not.

**Comment by Falx** [comment]
I'm fine with that fix and it sounds like it should fix it. Currently a breaking issue for us, so I would love to see this patched in ;-)

**Comment by ctron** [comment]
Do you have a quick test case which I could use?

**Comment by Falx** [comment]
You mean in code? Or some steps to reproduce?
I only encounter this via the upload plugin of jenkins..

**Comment by ctron** [comment]
I meant consuming the bundles. Which triggers the 404 error.

I did make a setup now with bndtools, added the repository as `http://localhost:8080/r5/obr1` and it works now (`obr1` is my alias).

**Comment by ctron** [comment]
Ok, a test with Apache Karaf and OBR looks fine as well. So I think I can make a quick maintenance release.

**Comment by Falx** [comment]
Thanks man! I will check it out and report back here, first chance I get!

**Comment by ctron** [comment]
The plain download is uploaded. The YUM and APT repository will take a few more minutes.

**Comment by ctron** [comment]
And thanks for reporting this!

**Comment by Falx** [comment]
I just tested it. It works! Simple upgrade via apt-get update.. Thanks so much!
