### ISSUE TITLE
Switch from Pax Web to some other OSGi HttpService implementation

### ISSUE THREAD

**Issue by ctron** [eclipse/packagedrone#36]
Currently Package Drone uses the Pax Web OSGi HttpService. However Pax Web has a few serious issues with re-registering Servlets, has a few bugs internally, does not implement the OSGi R6 HttpService patterns.

In addition to that it is pretty hard to get in contact with the project updates and bug fixes seem rare.

The most nasty bug Package Drone currently struggles with is the inability to re-register a servlet under the same name. This will require a restart of Package Drone whenever an HTTP endpoint trigger is being re-configured.

See also:
* ctron/package-drone#79
* https://ops4j1.jira.com/browse/PAXWEB-935
* https://groups.google.com/forum/#!topic/ops4j/55lPznD6qQM

**Comment by ctron** [comment]
Currently I do see two possible options

1. Switch back to Equinox Http Service
2. Switch to Apache Felix HTTP Service

Both solutions claim to provide OSGi R6 compatible HttpService and Http Whiteboard implementations. This should suffice for Package Drone at the present state and would allow for a plain OSGi approach.

The issue with the Equinox Http Service seems to be solved: [467859](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467859)

**Comment by maggu2810** [comment]
> it is pretty hard to get in contact with the project

Do you mean it is hard to get in contact with a Pax Web maintainer? Can't confirm that statement.

> The most nasty bug Package Drone currently struggles with is the inability to re-register a servlet under the same name.

IIRC that is already solved.

**Comment by maggu2810** [comment]
Perhaps the first one:
* https://ops4j1.jira.com/browse/PAXWEB-935
* https://ops4j1.jira.com/browse/PAXWEB-909
* https://ops4j1.jira.com/browse/PAXWEB-912

**Comment by ctron** [comment]
Well the Eclipse Foundation and myself tried a few times to get in contact with the project. Without any reply.

Trying to get access to their JIRA points me to broken Web UI like this: 

----- see image -----
![pax1](https://cloud.githubusercontent.com/assets/202474/13137019/7cbda7ba-d61e-11e5-8d75-b742878b659c.png)
----- see image -----

Various locations of Pax Web talk about Jetty 8 and Jetty 6. We currently are at Jetty 9.3. And I am still waiting for OSGi R6 -> https://groups.google.com/forum/#!topic/ops4j/55lPznD6qQM

I don't want to blame anyone! That is not what I'm saying! And I also do know how hard it is to keep an web page updated! But I would rather like to invest the time I have in Package Drone than working on Pax Web.

**Comment by maggu2810** [comment]
I have looked at: http://ops4j.github.io/pax/web/
If I press on the SNAPSHOT link I see an overview over the Jetty versions used in the different Pax Web versions: http://ops4j.github.io/pax/web/SNAPSHOT/index.html
I don't know if the versions are correct.

JIRA looks good for me: https://ops4j1.jira.com/projects/PAXWEB/issues/

I am very sure, that you do not blame anyone.
This was not my understanding. It is okay (for me) if you switch.
The only thing I want to state, is that my experiences differ from yours.

**Comment by ctron** [comment]
Yes, I can read-access the JIRA, but not comment, create new ones or make any other modifications.

This seems to be Pax Web 6.0, which is not ready for prime time though ... 

[1] talks about Jetty 8 and Pax web 4.x, [2] about Jetty 6.x

I mean, I do know it is working with Jetty 9.2.x ... 

Anyway, I am not sure Equinox OSGi R6 support is in a better condition. There was a good reason for switching _towards_ Pax Web!

But keeping track of Pax Web is quite a time consuming task.

Still, you are right! I will give Pax Web 4.1.5 another try, we are currently at 4.1.2!

[1] https://ops4j1.jira.com/wiki/display/paxweb/Pax+Web
[2] https://ops4j1.jira.com/wiki/display/paxweb/FAQ

**Comment by maggu2810** [comment]
On Karaf I am using Pax Web 4.2.4 and Jetty 9.2.14.v20151106

I would assume there is Pax Web 4.2.5 using Jetty 9.2.14.v20151106.
See pom.xml of tag web-4.2.5:
* https://github.com/ops4j/org.ops4j.pax.web/blob/web-4.2.5/pom.xml#L14
* https://github.com/ops4j/org.ops4j.pax.web/blob/web-4.2.5/pom.xml#L79

**Comment by ctron** [comment]
According to their page [1], the latest releases are 4.2.0 and 4.1.4 ...

[1] https://ops4j1.jira.com/wiki/display/paxweb/Download

**Comment by ctron** [comment]
Ok .. so you are right! Upgrading to Pax-Web 4.2.5 did solve the Servlet registration issue! So thanks point this out to me!

**Comment by ctron** [comment]
So I will close this one and take a second approach on that topic :-)
