### ISSUE TITLE
Jetty Run Configuration Error

### ISSUE THREAD

**Issue by addiittya2006** [eclipse/packagedrone#38]
I am stuck here and able to reproduce this error even on a fresh Install.
I installed and successfully setup my development Environment on a Linux Machine but not able to do it on my Mac.
Is there anything done wrong?
I tried invalidating all caches, still persistent.
<img width="1440" alt="screen shot 2016-02-17 at 11 46 46" src="https://cloud.githubusercontent.com/assets/7330961/13101361/e6af31ba-d56b-11e5-9f78-3fb06f158647.png">

**Comment by ctron** [comment]
I have to say, I never tried it on a Mac. It seems like that there is some issue with the path getting mixed up with the main class name. I've never seen that before.

The problem is, since I don't have a Mac, I am not sure how to reproduce this. I will try and see what I can do.

**Comment by addiittya2006** [comment]
I Solved this Issue.
Earlier i was trying to install and run through the Eclipse Installer Oomph.
Maybe Something was missing on the package or whatever.
But it works now with a complete Eclipse Committers Package downloaded from the Website.
It is not a bug in package drone package but while cloning and building with Oomph downloaded Eclipse.
This issue may be Closed.
