### ISSUE TITLE
[releng] Add support to Continuous Integration for Pull Request validation

### ISSUE THREAD

**Issue by jeandersonbc** [eclipse/packagedrone#39]
Besides the existing hourly building (https://hudson.eclipse.org/package-drone/job/package-drone/), it would be beneficial to have a pull request validation.

The main contributions to this would be:
* Not necessary to fetch changes and run tests for a proposed patch
* Sometimes, contributors may forget to test their changes. If the programmer had a quick feedback after creating a merge request, he/she would save time by being able to quickly figure what was wrong instead of waiting to someone or the hourly CI.

I had a previous experience with Travis CI and I could help with this one.

**Comment by ctron** [comment]
Since we did have a travis ci build in the past, this should not be a big deal. I just checked and the file is still present.

I did send out an e-mail to "Eclipse Webmaster" which can administer the GitHub repository.

**Comment by ctron** [comment]
Let the builds begin ;-)

[![build shield](https://api.travis-ci.org/eclipse/packagedrone.svg)](https://travis-ci.org/eclipse/packagedrone)

**Comment by ctron** [comment]
Still this won't work until travis-ci/travis-ci#4872 is fixed :-(

**Comment by jeandersonbc** [comment]
Is this the reason it was previously removed?

**Comment by ctron** [comment]
No, the reason for that was the move to Eclipse. We have a Hudson instance there, but no support for PR builds. And you (as a project lead) don't get admin access to the GitHub repository. Which is ok for me, but so you cannot simply add the travis-ci trigger. But now it is done ... travis-ci does not support Maven 3.3 :(

**Comment by ctron** [comment]
Waiting for travis-ci/travis-ci#4872

**Comment by ctron** [comment]
Ok, bootstrapping our own maven version works.
