### ISSUE TITLE
Add a modal "are you sure" dialog do the PGP managed key delete action

### ISSUE THREAD

**Issue by ctron** [eclipse/packagedrone#41]
In the "PGP Signing" (managed version) view, there is a delete button which will delete the PGP key from the system. Each destructive operation should have a red action button and a modal dialog asking for confirmation.

The action does have a red trash button, but there is no modal dialog up until now. This has to be fixed.

**Comment by jeandersonbc** [comment]
Agreed. Not to mention that the user is not aware about the consequences of a destructive action.
Could you assign this to me @ctron ?

**Comment by ctron** [comment]
Sadly no .. but this is just a limitation by GitHub. This works different with organization repositories.

So noted: you are working on it. And thanks for that! :+1:

**Comment by jeandersonbc** [comment]
More details here https://github.com/eclipse/packagedrone/pull/43 :smile:
