### ISSUE TITLE
Duplicated artifacts in the same channel

### ISSUE THREAD

**Issue by jeandersonbc** [eclipse/packagedrone#42]
Hi,

I was playing with Package Drone when by accident I selected the same Jar file twice.
I noticed that the system didn't handle my bad submission.

I continued to test this functionality and I also noticed that even if I not select any file and press upload, the system doesn't show any warning message. See the attached images for more details:

1. Empty form
![emptydata](https://cloud.githubusercontent.com/assets/2225536/13287896/0c355d8e-dae8-11e5-87d1-c3af208ae3ef.png)

2. Backend handler
![emptydebugger](https://cloud.githubusercontent.com/assets/2225536/13287897/0e8c0b46-dae8-11e5-868c-89ae77b15551.png)

3. Operation result
![result](https://cloud.githubusercontent.com/assets/2225536/13287899/116d92bc-dae8-11e5-9229-a54266f83780.png)

Is this the expected behavior?

**Comment by jeandersonbc** [comment]
PS.: See the last printscreen for duplicated uploads

**Comment by ctron** [comment]
Yes it is :)

In general there is no limitation on duplicates. However some aspects may veto that by throwing an exception in their code and rolling back the modification by that.

The next version will bring "triggers", which can hooked in various phases of repository modifications. And there will be one trigger which allows to ignore or fail an addition based on a set of conditions, e.g. enforcing a unique debian/OSGi version or so.
