### ISSUE TITLE
remove firewalld dependency

### ISSUE THREAD

**Issue by ruckc** [eclipse/packagedrone#46]
Why does the RHEL7 rpm have a dependency on firewalld?  It seems like a package manager should be fairly independent from a specific firewall configuration implementation.

**Comment by ctron** [comment]
Because it provides a firewall rule and activates it during the launch. What alternative is there on RHEL7?

**Comment by ruckc** [comment]
There is the normal iptables, but the better answer would be providing the firewall configuration file, and not requiring the hard dependency.

**Comment by ctron** [comment]
Hm .. so looking at the documentation of RHEL7, the way to go seems to be "firewalld" [1].

But I also just checked the contents of `openssh-server` and `httpd` from CentOS and neither one declares a dependency on `firewalld`.

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-Security_and_Access_Control.html

**Comment by ctron** [comment]
will be in version 0.13.0
