### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by ruckc** [eclipse/packagedrone#48]
I found the old ctron Upload-API wiki page, but was wondering if there was a bigger API?

I'm looking for a HEAD request that would let me know if an artifact with a certain name already was imported.  Or when trying to upload an artifact with the same name if the Upload API would throw an 4xx status code (422 Unprocessable Entity, 409 Conflict, or 403 forbidden).

Also would like a channels list API, and a channel listing API.

P.S. i'm potentially able to help with this depending on some other time commitments.

**Comment by ctron** [comment]
At the moment there is other API, see also #9. Hopefully in the future.
