### ISSUE TITLE
Export Channel Exception

### ISSUE THREAD

**Issue by kdoteu** [eclipse/packagedrone#5]
When I want to export any Channel I get the following Exception.

Causing exception:

*java.lang.ClassNotFoundException: org.eclipse.packagedrone.utils.io.IOConsumer cannot be found by org.eclipse.packagedrone.repo.channel.impl_1.0.0.20151126-0948*

Full StackTrace: [packagedrone_exportChannelException.txt](https://github.com/eclipse/packagedrone/files/79642/packagedrone_exportChannelException.txt)

*PackageDroneVersion: Package Drone 0.12.0.20151207-1732*

Hope this feature isn't reported in the other repository, but could not find any hint for it.

**Comment by ctron** [comment]
Could you try out a more recent build. The fix should be in commit 1917a398b11b84bdd7845cc6734269d5797be732. So Any version after 2015-12-15 should be fine.

**Comment by kdoteu** [comment]
After upgrading to Package Drone 0.12.0.20151216-1114 the problem is solved.

**Comment by ctron** [comment]
And so you just closed the first issue in this repository :+1:

Thanks!

**Comment by kdoteu** [comment]
Glad to see that this project is going straight forward. Will see if I could help more then just reporting errors and features ;D

**Comment by ctron** [comment]
Reporting errors and requesting features very helpful as well. Many people just drop things because of some hiccup. So thanks for helping!

Of course I will never complain about incoming pull requests :grin:
