### ISSUE TITLE
 Children links in relation tab are wrong

### ISSUE THREAD

**Issue by nfalco79** [eclipse/packagedrone#52]
When I select an artifact to view details, in the tag Relations it show me children links.
These link has a wrong url:
> http://{host}:{port}/artifact/{artifactId}/view

this URL is missing of the channel information. The correct URL is 
> http://{host}:{port}/channel/{channelId}/artifact/{artifactId}/view

Also refer to [eclipse bug 492710](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492710)

**Comment by ctron** [comment]
Thanks for reporting!

**Comment by ctron** [comment]
It will be in the integration builds in a few minutes and of course in the final release.
