### ISSUE TITLE
No dialog appear deleting a resource from a channel

### ISSUE THREAD

**Issue by nfalco79** [eclipse/packagedrone#55]
When I click delete link of a resource in a channel no dialog appears to confirm deletion.

Should be safer add a confermation dialog as in PR #43.

**Comment by ctron** [comment]
+1 ... although it has it advantages ;-)

**Comment by ctron** [comment]
Ok now #17 gets even more important ;-)

**Comment by ctron** [comment]
this one will be in the final 0.13.0 release
