### ISSUE TITLE
Help page for p2 repository does not work when user is logged in

### ISSUE THREAD

**Issue by nfalco79** [eclipse/packagedrone#57]
I have install the 0.12.1.20160211-1555 version.
I create a channel with follow aspects:
* OSGi
* P2 Metadata Generator
* P2 Repository
* P2 Unzip Generator

To know what is the p2 URL I go to the help p2 page.
If I navigate it as anonymous user then I show the correct page.
![p2help_ok](https://cloud.githubusercontent.com/assets/4160180/15014114/59ab6f56-1204-11e6-9e04-9d9e60b2cf25.jpg)

While if I logged in (I have MANAGER role) this is the page I show
![p2help_wrong](https://cloud.githubusercontent.com/assets/4160180/15014123/6cf00694-1204-11e6-8d68-1f00c701f033.jpg)

_I also notice that the help page URL for Maven page is help.maven (dot) instead (slash) such as help/p2 or help/api_

**Comment by ctron** [comment]
Thank again for reporting!

Yes, the URL naming is for from consistent. But I also don't want to touch if before the next release ;-)
