### ISSUE TITLE
Deleting artifact in unlock channel stacktrace page is shown

### ISSUE THREAD

**Issue by nfalco79** [eclipse/packagedrone#58]
When I lock a channel and I try to drop an artifact it show me a nice error message that channel is locked.
Instead if I try to delete artifact using page link it goes in internal server error showing me the usual java stacktrace page
> Caused by: java.lang.IllegalStateException: Channel is locked

I think a similar error message should appear to advise that channel is locked and the operation is not permitted or maybe disable the delete link.

**Comment by ctron** [comment]
Thanks for sending in all the reports! I really appreciate it!

**Comment by ctron** [comment]
That might not be a proper solution, but it does improve the situation :wink:
