### ISSUE TITLE
Absolute URLs does not allow apache reverse proxy remap context path different than root

### ISSUE THREAD

**Issue by nfalco79** [eclipse/packagedrone#59]
Out IT has try to install package drone as p2 repository.
We would configure apache to serve package drone on http://myserver/pdrone -> http://localhost:8080/ (pdrone to internal root context path). Other software are in that server and mapped on different context path.
The reverse proxy show only the main page, all reference the HTML page are absolute
> src="/resources..."

so all resources are not loaded because browser lookup them on _http://myserver/pdrone_ instead _http://myserver/pdrone/resource_.
Looking the code there are some URL build with **${pageContext.request.contextPath} + "/relativePath"** (I do understand how to change contextPath using config file) other as **src="/channel"** so they never work on different context path than root.

Relative URL should work fine.
We would avoid use a different hostname (virtualhost), please consider that this restriction it's an IT pain for the way on how they would deploy the software.

**Comment by nfalco79** [comment]
Sorry I did not look for existing open issue #47

**Comment by ctron** [comment]
A workaround for this might be the Apache "mod_proxy_html" module [1]

https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html

**Comment by ctron** [comment]
If you have any ideas for a good solution, please let me know. I switched the issue over to #47
