### ISSUE TITLE
Deployment with another user (only can be deploy with "deploy" user)

### ISSUE THREAD

**Issue by guel135** [eclipse/packagedrone#63]
I make may issue in the incorrect repository. I copy my message
> Hello, 
> First of all, thank you for package drone is a tool that help us a lot in our company making the things easier. 
> In our company we use generated code and when we develop new things we use a codegen-staging channel. 
> We wanted to have another different user to make this staging channel working with our proxy that also requires authentication and we can only pass it having the same user and password in booth sides invalided us to use the same user with several passwords.
> 
> We dont want to expose the deployment key for all the developers since we work with external developers.
> Many thanks for your help and it is only a improvement for us that not need to be quick. And also will be a lot more important features.
> 
> Keep making this good work.

Then Ctron replies

> Thank you for the positive feedback :+1:
> 
> So the proxy also requires HTTP basic authentication?

And now my message:
We are using authentication HTTp basic but we want to keep the user deploy only for the jenkins and then developers will have access to a codegen-staging channel with another user password. I know we can use another password but since our proxy also requires it the only way to pass is have the same user and password in the proxy and in packagedrone.
Then we dont need to expose the password to the developers because it will be only in the jenkin maven setting.

Many thanks,
Miguel

**Comment by ctron** [comment]
I am still not sure if fully understand. So you do want to use the "deploy" user with different passwords? One for the proxy and one for package drone?

**Comment by guel135** [comment]
Hello Jens,
I only want to have the option to use another users (not only "deploy")
then I can pass my proxy without problems.

2016-06-06 16:25 GMT+02:00 Jens Reimann <notifications@github.com>:

**Comment by ctron** [comment]
Ah, I see.

**Comment by ctron** [comment]
So I guess the solution would be to allow just any user with the right deployment token.

**Comment by guel135** [comment]
My solution could be deploy with another user call "Staging" or wherever is
need instead to need to use always "Deploy" user

2016-06-07 8:15 GMT+02:00 Jens Reimann <notifications@github.com>:
