### ISSUE TITLE
R5/OBR repository and custom capabilities

### ISSUE THREAD

**Issue by wkerckho** [eclipse/packagedrone#65]
I would like to use package drone as an OGSi R5 repository with some bundles that express custom capabilities. 

E.g. The bundle test.exporter provides a limeds.link resource with the id test.exporter.FunctionA by adding the following manifest entry: 
```Provide-Capability: limeds.link;limeds.component.id:String="test.exporter.FunctionA";limeds.component.version:String="000001000"```

Another bundle then requires this resource, by adding the following manifest entry:
```Require-Capability: limeds.link;filter:="(&(limeds.component.id=test.exporter.FunctionA)(&(limeds.component.version>=000001000)(!(limeds.component.version>=001000000))))";effective:=resolve```

Using bnd, I can create a repository that supports this custom capability (see attached [bnd-index.txt](https://github.com/eclipse/packagedrone/files/312054/bnd-index.txt) file), but package drone seems to ignore these capabilities and requirements statements (see attached [packagedrone-index.txt](https://github.com/eclipse/packagedrone/files/312056/packagedrone-index.txt)).

**Comment by ctron** [comment]
This is true. If you can make me a simple sample (or provide the one you mentioned) I think I can make a quick fix to that.

**Comment by wkerckho** [comment]
This is the link to the repo that was generated with bnd: https://dl.dropboxusercontent.com/u/1899207/limeds-test/index.xml

I hope this can help, otherwise I'm prepared to upload a more detailed example tomorrow if you tell what exactly you need.

Thanks for looking into this!

**Comment by ctron** [comment]
I would need some sort of full blown example. I did try with the "equinox OSGI" core bundle, which also uses capabilities. And I do think that I got most of the logic done.

However I would like to test your use case, unless you want to check out Package Drone yourself. Or I provide you with a local build. And you do the testing. I understand if you cannot hand out your software. And if you prefer you can also send my a link via e-mail.

**Comment by wkerckho** [comment]
I will try to test the fix by checking out the latest master. I'll keep you posted!

**Comment by wkerckho** [comment]
Actually, if you could provide a local build, that would be nice (I'm having some trouble getting it up and running from source).

**Comment by ctron** [comment]
Here is the download [1]

This is not a final release nor a version provided by the Eclipse Foundation. And the link will stop working in 20 days or after 20 downloads.

[1] https://tresor.it/s#y4yvjhJRM5hnI2Q5QRx7Gg

**Comment by wkerckho** [comment]
The fix works!

The expected entries appear in the R5 index and I can successfully use the repo to deploy the bundles with custom capabilities to an OSGi container.

Thank you very much!

**Comment by ctron** [comment]
So I will close this issue once the M1 for 0.14.0 is out.
