### ISSUE TITLE
0.14 release?

### ISSUE THREAD

**Issue by Falx** [eclipse/packagedrone#79]
Wasn't the 0.14 release supposed to be out since yesterday?

**Comment by ctron** [comment]
Yes ... But unfortunately I haven't heard back from the Eclipse release review [1]. 

I need to check ...

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=496953

**Comment by ctron** [comment]
The release review has been re-scheduled: 2016-09-07 [1] .. next week. Sorry for that. In the end it was my fault!

[1] https://projects.eclipse.org/projects/technology.package-drone/releases/0.14.0
