### ISSUE TITLE
0.14 upload issue

### ISSUE THREAD

**Issue by ruckc** [eclipse/packagedrone#81]
Ran into the issue with the current 0.14 release from the hudson instance and the latest jenkins & jenkins plugin.  This broke with both  the V3 uploader and the V2 uploader.  Nothing correlating to this in the package-drone-server standard output/error.

V3:
{code}
Package Drone Server URL: http://packagedrone.example.com
Uploading using Package Drone V3 uploader
API endpoint: http://packagedrone.example.com/api/v3/upload/archive/channel/puppetexplorer
Call returned: HTTP/1.1 500 Server Error
ERROR: javax.xml.transform.TransformerFactory: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
Build step 'Package Drone Deployer' changed build result to FAILURE
{code}

V2:
{code}
Package Drone Server URL: http://packagedrone.example.com
Uploading using Package Drone V2 uploader
ERROR: Failed to upload puppetexplorer-2.0.0-SNAPSHOT20160901220313.noarch.rpm: 500 Server Error = javax.xml.transform.TransformerFactory: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
{code}

**Comment by ctron** [comment]
Very strange. I will dig into this before the release! Thanks for reporting!

**Comment by ctron** [comment]
Just to be sure. Is that something which happens in the Jenkins Plugin, or in Package Drone itself.

**Comment by ruckc** [comment]
I think Jenkins plugin, nothing logs in package drone logging.

**Comment by ctron** [comment]
So it should be moved to [ctron/package-drone-jekins](https://github.com/ctron/package-drone-jenkins) then.

**Comment by ruckc** [comment]
I just relooked at it appears due to a server error, the javax.xaml.transform.TransformerFactory is on the jenkins plugin because the server has a 500 error.

```
Package Drone Server URL: http://packagedrone.example.com
Uploading using Package Drone V3 uploader
API endpoint: http://packagedrone.example.com/api/v3/upload/archive/channel/packagename
Call returned: HTTP/1.1 500 Server Error
ERROR: javax.xml.transform.TransformerFactory: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
Build step 'Package Drone Deployer' changed build result to FAILURE
Finished: FAILURE
```

**Comment by ruckc** [comment]
Further testing with curl below, looking at this in detail, did you change anything related to xalan?  It looks like in XmlToolsFactoryImpl.java your hardcoding to the xalan provided implementation, instead of using the JRE's default with TransformerFactory.newInstance().
```
[root@packagedrone ~]# curl -v -XPUT --data-binary @org.eclipse.packagedrone.server-0.14.0-1.1.el7.noarch.rpm http://deploy:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@packagedrone.example.com/api/v2/upload/channel/loghoard/org.eclipse.packagedrone.server-0.14.0-1.1.el7.noarch.rpm
* About to connect() to packagedrone.example.com port 80 (#0)
*   Trying 10.0.0.14...
* Connected to packagedrone.example.com (10.8.8.14) port 80 (#0)
* Server auth using Basic with user 'deploy'
> PUT /api/v2/upload/channel/loghoard/org.eclipse.packagedrone.server-0.14.0-1.1.el7.noarch.rpm HTTP/1.1
> Authorization: Basic ZGVwbG95Ojk3ZWRkZGE1YmFlNTNjZWYwY2YxNDFhMZNiZTM4YWQ2Y2EwNJc3zTU4ZGJlOTMyMmYyOGQ3ZDdkOTlmMjE3OTQ=
> User-Agent: curl/7.29.0
> Host: packagedrone.example.com
> Accept: */*
> Content-Length: 35905112
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Server Error
< Date: Wed, 07 Sep 2016 00:46:37 GMT
< Content-Type: text/plain;charset=iso-8859-1
< Content-Length: 109
< Server: Jetty(9.3.10.v20160621)
* HTTP error before end of send, stop sending
<
javax.xml.transform.TransformerFactory: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
* Closing connection 0
```

**Comment by ctron** [comment]
Well the default lookup method with JRE is broken when using OSGi. The JRE internally caches the class name and, depending on which bundle does the look, it fails to locate the class. But xalan should be part of the distribution.

**Comment by ctron** [comment]
Ok .. Fixed! Thanks for reporting!
