### ISSUE TITLE
RPM meta information

### ISSUE THREAD

**Issue by t794104** [eclipse/packagedrone#86]
A small request; the RPM meta data retrieves the name, os, arch, version,. What iḿ missing too uniquely identify a RPM is the release. 

I think it's a one line fix in :  packagedrone/bundles/org.eclipse.packagedrone.repo.adapter.rpm/src/org/eclipse/packagedrone/repo/adapter/rpm/internal/RpmExtractor.java

by adding the 'RELEASE'.

thanks

**Comment by ctron** [comment]
Can you make a PR?
