### ISSUE TITLE
Open up API for better integration

### ISSUE THREAD

**Issue by Falx** [eclipse/packagedrone#9]
I am currently trying to integrate packagedrone in my continuous integration setup. It would be great to be able to access the API for some basic info.

E.g.
If I could access an overview in JSON via an endpoint of my current channels, I could show a selection box on my webpage to select to which channel the current setup should publish.

**Comment by ctron** [comment]
Definitely :+1:

**Comment by ctron** [comment]
My initial approach would be to use [1] as a REST platform and write up a few services.

The only important part is the matter of authentication and authorization.

[1] https://github.com/hstaudacher/osgi-jax-rs-connector

**Comment by kdoteu** [comment]
In our products we are using hstaudachers jax-rs-connector it is very good for implementing a rest-api. I would recommend that.

**Comment by ctron** [comment]
I just added a Google Summer of Code 2016 Idea to the list [1]. Maybe someone will volunteer :wink: 

[1] https://wiki.eclipse.org/Google_Summer_of_Code_2016_Ideas#Package_Drone:_Create_a_REST-based_API

**Comment by ctron** [comment]
@kdoteu we are using the same framework for Eclipse SCADA. And I do know that Eclipse SmartHome is using the same in their stack. So this would also be my first choice. But maybe there is something better out there :wink: 

I guess the biggest topic is the authentication and authorization area. The jax-rs-connector allows to inject a custom implementation, but you first need this implementation. And adding OAuth 2 or something like that could be a bit more effort than just registering a service with OSGi.

**Comment by ctron** [comment]
If did read an interesting post in the past. maybe this helps: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by Boggartfly** [comment]
@Falx I'm interested in doing this as a part of GSoC 2016. Hopefully that works out!

**Comment by Falx** [comment]
@Boggartfly That would be very nice!

**Comment by Boggartfly** [comment]
@ctron I'm willing to volunteer as a GSoC 2016 project!

**Comment by ctron** [comment]
@Boggartfly I am happy to hear that. Let me know if you need any help.

**Comment by Boggartfly** [comment]
Lets see how the proposal goes!

**Comment by krishnilak** [comment]
Hi, I would like to volunteer on this idea in GSOC 2016.

**Comment by ctron** [comment]
Although this proposal was not picked, another one was. Which also does require some JAX-RS infrastructure. So although there is not API itself, the basic infrastructure for JAX-RS will be added in 0.14.0. Unless there are some CQs which get rejected.

This also paves the way to creating other remote APIs based on the same technology.

So if your are still interested I would be happy to work with you on some API.

**Comment by krishnilak** [comment]
Hi Jens,
Yes I would like to work on. Can I hear more info?
Thank You

**Comment by ctron** [comment]
@krishnilak thanks for the offer, but I actually meant @Falx, since he seemed to have a specific use case to work on.

But of course you are welcomed to help if you like.

**Comment by Falx** [comment]
Currently I only use two package drone channels in my build system, so for me this is not a priority anymore. However I look forward to any developments on the package drone project.
